routes: rename login manager variable
previously named `login` to fix shadowing issue, with the `login` endpoint renamed as
`loginRoute`. this caused another issue:

werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'routes.loginRoute' instead?

`loginRoute` really ought to be called `login` anyways, thus we rename `login` as `login_manager`.